apiVersion: mhcp/v1
kind: DomainBundle
metadata:
  domain: claims
  version: 1

spec:
  pipelineTemplates:
    - name: ingestion_transform_enrich_load
      steps:
        - name: ingestion
          type: INGESTION
        - name: transformation
          type: TRANSFORMATION
          dependsOn: [ingestion]
        - name: enrichment
          type: ENRICHMENT
          dependsOn: [transformation]
        - name: load
          type: LOAD
          dependsOn: [enrichment]

  transformations:
    - name: claims_claim_header_fhir_to_canonical
      input:
        format: FHIR
        resource: ExplanationOfBenefit
      output:
        format: CANONICAL_JSON
        schema: claims.claim_header.v1
      rules:
        - type: MAP
          from: id
          to: claimId
        - type: MAP
          from: created
          to: createdAt
        - type: CONSTANT
          to: sourceSystem
          value: EPIC

    - name: claims_claim_line_fhir_to_canonical
      input:
        format: FHIR
        resource: ExplanationOfBenefit
      output:
        format: CANONICAL_JSON
        schema: claims.claim_line.v1
      rules:
        - type: MAP
          from: id
          to: claimLineId
        - type: MAP
          from: created
          to: createdAt

  datasets:
    - name: claims.claim_header
      source:
        entity: ExplanationOfBenefit
        extractionMode: INCREMENTAL
        checkpointKey: createdAt
        # ✅ connectionRef optional (inherits from ConnectionBundle defaults)
        # connectionRef: claims_epic_fhir_conn

      pipeline:
        templateRef: ingestion_transform_enrich_load

      transformation:
        ref: claims_claim_header_fhir_to_canonical

      read:
        mode: batch
        format: json
        options:
          multiLine: "false"

      write:
        format: delta
        mode: UPSERT
        path: s3://mhcp-prod/claims/claim_header/
        options:
          mergeSchema: "true"
        primaryKey:
          - claimId

    - name: claims.claim_line
      source:
        entity: ExplanationOfBenefit
        extractionMode: INCREMENTAL
        checkpointKey: createdAt

      pipeline:
        templateRef: ingestion_transform_enrich_load

      transformation:
        ref: claims_claim_line_fhir_to_canonical

      read:
        mode: batch
        format: json
        options:
          multiLine: "false"

      write:
        format: delta
        mode: UPSERT
        path: s3://mhcp-prod/claims/claim_line/
        options:
          mergeSchema: "true"
        primaryKey:
          - claimLineId
