apiVersion: mhcp/v1
kind: EnrichmentBundle
metadata:
  domain: claims
  version: 1

spec:
  enrichments:
    - name: claims_member_lookup
      strategy: LOOKUP
      inputKeys:
        - patientRef

      lookup:
        type: JDBC
        connectionRef: claims_member_db_conn
        query: |
          SELECT member_id, member_segment
          FROM member_master
          WHERE patient_ref = :patientRef

      outputFields:
        - memberId: member_id
        - memberSegment: member_segment

    - name: common_code_mapping
      strategy: LOOKUP
      inputKeys:
        - code

      lookup:
        type: JDBC
        connectionRef: claims_member_db_conn
        query: |
          SELECT standard_code, description
          FROM code_mapping
          WHERE source_code = :code

      outputFields:
        - standardCode: standard_code
        - description: description
